#!/bin/bash

if [[ -z "$SDK" ]]; then
    echo 'Exporting build environment variables...'
    export SDK='iphonesimulator10.2'
    export SCHEME='RideShare'
    export WORKSPACE='RideShare.xcworkspace'
    export DESTINATION='OS=10.2,name=iPhone 7'
    export CONFIGURATION='Debug'
fi

rm -rf ./build

xcodebuild build \
    -workspace "$WORKSPACE" \
    -scheme "$SCHEME" \
    -sdk "$SDK" \
    -destination "$DESTINATION" \
    -derivedDataPath build \
    ONLY_ACTIVE_ARCH=YES \
    -configuration "$CONFIGURATION" | bundle exec xcpretty;

exit "${PIPESTATUS[0]}"
