#!/bin/bash

echo "REPO_SLUG = $REPO_SLUG"
echo "PR_NUMBER = $PR_NUMBER"

./Pods/SwiftLint/swiftlint lint --reporter json > swiftlint-report.json || false

if [[ -z "$PR_NUMBER" ]]; then
    echo 'Not in a Pull Request, skip report.'
else
    bundle exec linterbot "$REPO_SLUG" "$PR_NUMBER" < swiftlint-report.json
fi
