#!/bin/bash

if [[ -z "$SDK" ]]; then
    echo 'Exporting build environment variables...'
    export SDK='iphonesimulator10.3'
    export DESTINATION='OS=10.3,name=iPhone 7'
    export CONFIGURATION='Debug'
fi

export WORKSPACE='MVVM.xcworkspace'
export SCHEME='MVVM'

xcodebuild build \
    -workspace "$WORKSPACE" \
    -scheme "$SCHEME" \
    -sdk "$SDK" \
    -destination "$DESTINATION" \
    -derivedDataPath build \
    ONLY_ACTIVE_ARCH=YES \
    -configuration "$CONFIGURATION" | bundle exec xcpretty

exit "${PIPESTATUS[0]}"
